version: "3.9"

services:
    frontend:
        image: ghcr.io/jordynkaplan/usopc:main
        ports:
            - "80:80"
        networks:
            main:
                aliases:
                    - frontend

networks:
    main:
        driver: bridge
